name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-03"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNGU1Yjc1N2MtOGQxOS00MDMzLWE2NGEtMzdiYjI5YWQwNGMwIiwidGVuYW50X2lkIjoiYzlhOTI0Y2UzYTYyMzA0YTc0OWI1NzhjMDkwNTBjMDRjNzJjYWE4ZTlmZWI2ODhmNDAxMTllNmMwZmVhNDk4ZCIsImludGVybmFsX3NlY3JldCI6IjA1MTEyODU2LWMyZDItNDYzMS1iYzhmLTQ5MWYyYmUwNzc1OCJ9.9oQpUoomKqne778N8gSofm4v6vCkszlE9QT1aLlfil0"
